apiVersion: v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: prometheus-k8s-federate
  namespace: openshift-monitoring
spec:
  path: /federate
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: Reencrypt
  to:
    kind: Service
    name: prometheus-k8s
