apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: prometheus-k8s-kube-rbac-proxy-web
  namespace: openshift-monitoring
stringData:
  config.yaml: |-
    "authorization":
      "resourceAttributes":
        "apiGroup": "monitoring.coreos.com"
        "name": "k8s"
        "namespace": "openshift-monitoring"
        "resource": "prometheuses"
        "subresource": "api"
      "static":
      - "path": "/metrics"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s"
        "verb": "get"
      - "path": "/federate"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s"
        "verb": "get"
      - "path": "/federate"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:telemeter-client"
        "verb": "get"
type: Opaque
