apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: alertmanager-main
    app.kubernetes.io/part-of: openshift-monitoring
  name: alertmanager-main-proxy
  namespace: openshift-monitoring
type: Opaque
