run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
    - test
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - depguard
    - errcheck
    - errorlint
    - bodyclose
    - exportloopref
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - gci

linters-settings:
  depguard:
    rules:
      # Name of a rule.
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use 'errors' or 'fmt' instead"
          - pkg: "golang.org/x/exp/slices"
            desc: "Use 'slices' instead"
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/openshift/cluster-monitoring-operator)
