run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
    - test
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - errcheck
    - bodyclose
    - exportloopref
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - gci

linter-settings:
  gci:
    - standard
    - default
    - prefix(github.com/openshift/cluster-monitoring-operator)
