apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/description: |-
      Expose openshift-state-metrics `/metrics` endpoints within the cluster on the following ports:
      * Port 8443 provides access to the OpenShift resource metrics. This port is for internal use, and no other usage is guaranteed.
      * Port 9443 provides access to the internal `openshift-state-metrics` metrics. This port is for internal use, and no other usage is guaranteed.
    service.beta.openshift.io/serving-cert-secret-name: openshift-state-metrics-tls
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
    k8s-app: openshift-state-metrics
  name: openshift-state-metrics
  namespace: openshift-monitoring
spec:
  clusterIP: None
  ports:
  - name: https-main
    port: 8443
    targetPort: https-main
  - name: https-self
    port: 9443
    targetPort: https-self
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: openshift-state-metrics
