apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: cluster-monitoring-view
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
