apiVersion: v1
data:
  ca.crt: ""
  ca.key: ""
  prometheus-server.crt: ""
  prometheus-server.key: ""
  thanos-querier-client.crt: ""
  thanos-querier-client.key: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: grpc-tls
  namespace: openshift-monitoring
type: Opaque
