apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: cluster-monitoring-operator
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: ""
    metricRelabelings:
    - action: drop
      regex: (apiserver|go_sched|workqueue)_.+
      sourceLabels:
      - __name__
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      insecureSkipVerify: false
      keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
      serverName: cluster-monitoring-operator.openshift-monitoring.svc
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-monitoring-operator
