apiVersion: v1
data:
  salt: ""
  token: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
    k8s-app: telemeter-client
  name: telemeter-client
  namespace: openshift-monitoring
type: Opaque
