apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/part-of: openshift-monitoring
  name: thanos-querier-kube-rbac-proxy-web
  namespace: openshift-monitoring
stringData:
  config.yaml: |-
    "authorization":
      "resourceAttributes":
        "apiGroup": "monitoring.coreos.com"
        "name": "k8s"
        "namespace": "openshift-monitoring"
        "resource": "prometheuses"
        "subresource": "api"
type: Opaque
