apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: thanos-ruler
    app.kubernetes.io/part-of: openshift-monitoring
  name: thanos-ruler-oauth-cookie
  namespace: openshift-user-workload-monitoring
type: Opaque
